### Obter todos os produtos
GET  http://localhost:3400/produtos
Content-Type: application/json
Authorization: 8f8c5397ab71941d3c657247f3ea684f 


### Obter o produto por id
GET  http://localhost:3400/produtos/1
Content-Type: application/json
Authorization: 8f8c5397ab71941d3c657247f3ea684f


### Cadastrar o produto
POST http://localhost:3400/produtos
Content-Type: application/json
Authorization: 8846b88fa80d2e6f03637d20c01fc33a 

{
    "nome": "Produto de exemplo",
    "valor": 200,
    "quantidadeEstoque": 10,
    "observacao": "Produto de exemplo",
    "dataCadastro": "2022-01-15T19:41:25.361Z"
}

### Atualizar produtos
PUT http://localhost:3400/produtos/1
Content-Type: application/json
Authorization: 8f8c5397ab71941d3c657247f3ea684f

{
    "nome": "Sapato Masculino",
    "valor": 200,
    "quantidadeEstoque": 10,
    "observacao": "Produto atualizado",
    "dataCadastro": "2022-01-15T19:41:25.361Z"
}


### Deletar produto por id
DELETE http://localhost:3400/produtos/1
Content-Type: application/json
Authorization: 8846b88fa80d2e6f03637d20c01fc33a 